apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-litellm-config
  labels:
    {{- include "litellm.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Files.Get "files/config.yaml" | indent 4 }}
