apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gmail-connector
  labels:
    {{- include "gmailconnector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "gmailconnector.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
